# The various options for vise. To override these settings, simply create
# ~/.config/vise/config.yaml and copy over whichever settings you want
# to override from here.


##################### Keyboard shortcuts ############################

normal mode keys:  # The keys used in normal mode
    forward: Alt+Right
    back: Alt+Left
    next_tab: Shift+Down
    prev_tab: Shift+Up
    close_tab: D
    ask:
        - ';'
        - ':'
        - 'Shift+:'
        - 'Shift+;'
    ask_open: O
    ask_tabopen: Shift+O
    search_forward: /
    search_back: 
        - '?'
        - 'Shift+?'
    next_match: N
    prev_match: Shift:N
    set_passthrough_mode: Ctrl+Z
    quickmark: G
    quickmark_newtab: Shift+G
    scroll_line_down: J
    scroll_line_up: K
    scroll_line_left: H
    scroll_line_right: L
    copy_url: Y
    paste_and_go: P
    paste_and_go_newtab: Shift+P
    reload: R
    hard_reload: Shift+R
    choose_tab: T
    follow_next: ']'
    follow_previous: '['
    exit_full_screen: Escape
    toggle_full_screen: F11


insert mode keys:  # The keys used in insert mode (i.e. when the cursor is in a text input field)
    exit_text_input: Escape
    edit_text: Ctrl+I
    fill_login_form: Ctrl+L

##################### Fonts ############################

fonts:
    families:
        # These define the font families used on websites that do not specify their own fonts. For example:
        # sans-serif: Liberation Sans
        # A value of "default" means to use the desktop environment font setting.
        # Note that the value of sans-serif is used as the general font for the interface
        standard: default
        fixed: default
        serif: default
        sans-serif: default
        cursive: default
        fantasy: default
        pictograph: default
    sizes:
        # Control the sizes of fonts. Should be numbers, in pixels. For example:
        # default-size: 16
        # A value of "default" means to use the default values from the desktop environment
        # Note that default-size also sets the font size for the fonts used in the interface
        # You can also specify hostname specific font sizes, like this:
        # default-size:
        #     mycomputer1: 14
        #     mycomputer2: 20
        #     *: 16
        minimum: default
        minimum-logical: default
        default-size: default
        default-monospace-size: default

##################### Colors ############################
#
# A value of "default" means use the colors specified by the desktop environment color scheme.

colors:
    tab tree background: darkGray
    tab tree foreground: black
    tab tree hover gradient start: "#e7effd"
    tab tree hover gradient end: "#cbdaf1"
    tab tree hover border: "#bfcde4"
    status bar background: black
    status bar foreground: white


##################### Misc ############################

# The editor to use to edit text fields. A value of "default" means use the
# environment variable EDITOR.
editor: default
